SERVER:
  USER: "test"
  PASS: "test"
  AUTH_ENABLED: false
  PORT: 8082
LOGGER:
  LOGLEVEL: TRACE
  GRAYLOG_ACTIVE: false
  GRAYLOG_SERVER: "localhost"
  GRAYLOG_STREAM: "VAT_ID_VALIDATOR"
  DISABLE_STDOUT: false
VALIDATOR:

EU_VIES:
  URL: "http://ec.europa.eu/taxation_customs/vies/services/checkVatService"
